import React, { useState } from 'react';
import { useWorkflow } from '../context/WorkflowContext';
import { 
  GitCommit, 
  CheckCircle2, 
  XCircle, 
  AlertTriangle, 
  ShieldAlert, 
  FileCode, 
  Clock, 
  ExternalLink,
  Copy,
  Check,
  ChevronRight,
  Sparkles,
  RotateCcw
} from 'lucide-react';

export const CodeChangesView: React.FC = () => {
  const { codeChange, approvePatch, rejectPatch, retryStage } = useWorkflow();
  const [viewMode, setViewMode] = useState<'split' | 'unified'>('unified');
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    const rawDiff = codeChange.lines
      .map((l) => `${l.type === 'add' ? '+' : l.type === 'del' ? '-' : ' '} ${l.content}`)
      .join('\n');
    navigator.clipboard.writeText(rawDiff);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-6">
      {/* Top Banner / Breadcrumb */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-cyber-border/40 pb-4">
        <div>
          <div className="flex items-center space-x-2 text-xs text-cyber-muted font-mono mb-1">
            <span>DevFlow AI</span>
            <ChevronRight className="w-3 h-3 text-cyan-500/50" />
            <span className="text-cyan-400">Autonomous Code Synthesis</span>
            <ChevronRight className="w-3 h-3 text-cyan-500/50" />
            <span className="text-white font-semibold">Git Patch Diff</span>
          </div>
          <h1 className="text-2xl font-bold tracking-tight text-white flex items-center space-x-3">
            <span>Synthesized Code Changes</span>
            <span className="text-xs px-2.5 py-0.5 rounded-full font-mono font-medium border bg-cyan-950/40 text-cyan-400 border-cyan-800/60">
              PR #142-FIX
            </span>
          </h1>
          <p className="text-sm text-cyber-muted mt-1">
            Autonomous minimal patch generated by Code Modification Agent with bounded validation.
          </p>
        </div>

        {/* Human In The Loop Action Gate */}
        <div className="flex items-center space-x-3 bg-cyber-dark/80 p-2 rounded-lg border border-cyber-border">
          {codeChange.approvedByHuman ? (
            <div className="flex items-center space-x-3 px-3 py-1.5 rounded-md bg-emerald-950/40 border border-emerald-500/40 text-emerald-400 text-xs font-mono">
              <CheckCircle2 className="w-4 h-4 text-emerald-400" />
              <div>
                <div className="font-semibold">HUMAN SIGN-OFF RECORDED</div>
                <div className="text-[10px] text-cyber-muted">
                  {codeChange.approvalTimestamp ? new Date(codeChange.approvalTimestamp).toLocaleTimeString() : 'Verified'}
                </div>
              </div>
              <button
                onClick={rejectPatch}
                className="ml-2 text-[10px] underline hover:text-emerald-200 transition-colors"
                title="Revoke sign-off and request revision"
              >
                Revoke
              </button>
            </div>
          ) : (
            <div className="flex items-center space-x-2">
              <button
                onClick={approvePatch}
                className="btn-cyber-primary flex items-center space-x-2 text-xs"
              >
                <CheckCircle2 className="w-3.5 h-3.5" />
                <span>Approve Patch</span>
              </button>
              <button
                onClick={rejectPatch}
                className="px-3 py-1.5 rounded-md text-xs font-mono bg-red-950/40 hover:bg-red-900/50 text-red-400 border border-red-800/50 transition-colors flex items-center space-x-1"
              >
                <XCircle className="w-3.5 h-3.5" />
                <span>Reject</span>
              </button>
            </div>
          )}

          <button
            onClick={() => retryStage('fix')}
            className="p-1.5 rounded-md text-cyber-muted hover:text-cyan-400 hover:bg-cyber-card transition-colors border border-transparent hover:border-cyber-border"
            title="Re-run Fix Agent"
          >
            <RotateCcw className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* Meta Specs Bar */}
      <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
        <div className="card-cyber p-4">
          <div className="text-xs font-mono text-cyber-muted mb-1 flex items-center space-x-1.5">
            <FileCode className="w-3.5 h-3.5 text-cyan-400" />
            <span>Target File</span>
          </div>
          <div className="text-sm font-semibold text-white font-mono truncate" title={codeChange.filePath}>
            {codeChange.filePath}
          </div>
          <div className="text-xs text-cyber-muted font-mono mt-1 flex items-center space-x-2">
            <span className="text-emerald-400">+{codeChange.additions} lines</span>
            <span>•</span>
            <span className="text-red-400">-{codeChange.deletions} lines</span>
          </div>
        </div>

        <div className="card-cyber p-4">
          <div className="text-xs font-mono text-cyber-muted mb-1 flex items-center space-x-1.5">
            <ShieldAlert className="w-3.5 h-3.5 text-cyan-400" />
            <span>Patch Risk Rating</span>
          </div>
          <div className="flex items-center space-x-2">
            <span className={`text-xs px-2.5 py-0.5 rounded font-mono font-bold uppercase ${
              codeChange.riskLevel === 'LOW' 
                ? 'bg-emerald-950/60 text-emerald-400 border border-emerald-800/60'
                : 'bg-amber-950/60 text-amber-400 border border-amber-800/60'
            }`}>
              {codeChange.riskLevel} RISK
            </span>
            <span className="text-[11px] text-cyber-muted">Minimal surgical diff</span>
          </div>
          <div className="text-[11px] text-cyber-muted mt-1 font-mono">0 breaking API changes</div>
        </div>

        <div className="card-cyber p-4">
          <div className="text-xs font-mono text-cyber-muted mb-1 flex items-center space-x-1.5">
            <GitCommit className="w-3.5 h-3.5 text-cyan-400" />
            <span>Synthesizer Model</span>
          </div>
          <div className="text-sm font-semibold text-white font-mono">
            Granite Code 34B
          </div>
          <div className="text-[11px] text-cyber-muted mt-1 flex items-center space-x-1">
            <Sparkles className="w-3 h-3 text-cyan-400" />
            <span>Multi-modal prompt context</span>
          </div>
        </div>

        <div className="card-cyber p-4">
          <div className="text-xs font-mono text-cyber-muted mb-1 flex items-center space-x-1.5">
            <Clock className="w-3.5 h-3.5 text-cyan-400" />
            <span>Verification Status</span>
          </div>
          <div className="flex items-center space-x-1.5 text-sm font-semibold text-emerald-400 font-mono">
            <CheckCircle2 className="w-4 h-4 text-emerald-400" />
            <span>47/47 Tests Passing</span>
          </div>
          <div className="text-[11px] text-cyber-muted mt-1 font-mono">+5 regression tests verified</div>
        </div>
      </div>

      {/* Rationale & Operational Notes Accordions */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <div className="card-cyber p-4 space-y-2">
          <div className="text-xs font-mono font-semibold uppercase tracking-wider text-cyan-400 flex items-center space-x-2">
            <Sparkles className="w-3.5 h-3.5" />
            <span>Fix Rationale</span>
          </div>
          <p className="text-xs text-cyber-muted leading-relaxed">
            {codeChange.rationale}
          </p>
        </div>

        <div className="card-cyber p-4 space-y-2">
          <div className="text-xs font-mono font-semibold uppercase tracking-wider text-cyan-400 flex items-center space-x-2">
            <AlertTriangle className="w-3.5 h-3.5 text-amber-400" />
            <span>Test Impact Analysis</span>
          </div>
          <p className="text-xs text-cyber-muted leading-relaxed">
            {codeChange.testImpact}
          </p>
        </div>

        <div className="card-cyber p-4 space-y-2">
          <div className="text-xs font-mono font-semibold uppercase tracking-wider text-cyan-400 flex items-center space-x-2">
            <RotateCcw className="w-3.5 h-3.5 text-cyan-400" />
            <span>Rollback Notes</span>
          </div>
          <p className="text-xs text-cyber-muted leading-relaxed">
            {codeChange.rollbackNotes}
          </p>
        </div>
      </div>

      {/* Diff Viewer Card */}
      <div className="card-cyber overflow-hidden">
        {/* Diff Header */}
        <div className="p-3 bg-cyber-dark/80 border-b border-cyber-border flex flex-wrap items-center justify-between gap-2">
          <div className="flex items-center space-x-3">
            <div className="flex items-center space-x-2 text-xs font-mono text-white">
              <FileCode className="w-4 h-4 text-cyan-400" />
              <span className="font-bold">{codeChange.filePath}</span>
            </div>
            <div className="flex items-center space-x-1.5 font-mono text-[11px]">
              <span className="px-2 py-0.5 rounded bg-emerald-950/70 text-emerald-400 border border-emerald-800/40">
                +{codeChange.additions}
              </span>
              <span className="px-2 py-0.5 rounded bg-red-950/70 text-red-400 border border-red-800/40">
                -{codeChange.deletions}
              </span>
            </div>
          </div>

          <div className="flex items-center space-x-2">
            <div className="bg-cyber-bg border border-cyber-border rounded p-0.5 flex items-center text-xs font-mono">
              <button
                onClick={() => setViewMode('unified')}
                className={`px-2.5 py-1 rounded transition-colors ${
                  viewMode === 'unified' ? 'bg-cyan-500/20 text-cyan-400' : 'text-cyber-muted hover:text-white'
                }`}
              >
                Unified
              </button>
              <button
                onClick={() => setViewMode('split')}
                className={`px-2.5 py-1 rounded transition-colors ${
                  viewMode === 'split' ? 'bg-cyan-500/20 text-cyan-400' : 'text-cyber-muted hover:text-white'
                }`}
              >
                Split View
              </button>
            </div>

            <button
              onClick={handleCopy}
              className="px-2.5 py-1 rounded text-xs font-mono bg-cyber-bg hover:bg-cyber-card border border-cyber-border text-cyber-muted hover:text-white transition-colors flex items-center space-x-1"
            >
              {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
              <span>{copied ? 'Copied!' : 'Copy Patch'}</span>
            </button>
          </div>
        </div>

        {/* Code Lines Rendering */}
        <div className="font-mono text-xs overflow-x-auto bg-[#040c16] p-2 leading-relaxed">
          {codeChange.lines.map((line, idx) => {
            const isAdd = line.type === 'add';
            const isDel = line.type === 'del';

            return (
              <div
                key={idx}
                className={`flex items-start transition-colors ${
                  isAdd
                    ? 'bg-emerald-950/30 text-emerald-200 border-l-2 border-emerald-500'
                    : isDel
                    ? 'bg-red-950/30 text-red-300 border-l-2 border-red-500'
                    : 'text-slate-300 hover:bg-cyber-dark/40 border-l-2 border-transparent'
                }`}
              >
                {/* Line Numbers */}
                <div className="w-12 select-none text-right pr-3 text-[11px] text-cyber-muted/50 font-mono">
                  {line.oldLineNumber || ''}
                </div>
                <div className="w-12 select-none text-right pr-3 text-[11px] text-cyber-muted/50 font-mono">
                  {line.newLineNumber || ''}
                </div>

                {/* Diff Prefix Sign */}
                <div className="w-6 select-none text-center font-bold">
                  {isAdd ? '+' : isDel ? '-' : ' '}
                </div>

                {/* Actual Code Content */}
                <div className="flex-1 whitespace-pre pl-2 overflow-x-visible">
                  {line.content}
                </div>
              </div>
            );
          })}
        </div>
      </div>

      {/* Human in the loop confirmation notice */}
      <div className="card-cyber p-4 border border-cyan-500/20 bg-gradient-to-r from-cyan-950/20 to-transparent flex items-center justify-between">
        <div className="flex items-center space-x-3">
          <div className="w-8 h-8 rounded-full bg-cyan-950/60 border border-cyan-500/40 flex items-center justify-center text-cyan-400">
            <CheckCircle2 className="w-4 h-4" />
          </div>
          <div>
            <div className="text-xs font-semibold text-white font-mono uppercase tracking-wider">
              Governance Requirement: Human Sign-off
            </div>
            <div className="text-xs text-cyber-muted mt-0.5">
              Enterprise policy mandates human approval before merging autonomous patches into protected trunk branches.
            </div>
          </div>
        </div>

        <div className="flex items-center space-x-2">
          {!codeChange.approvedByHuman ? (
            <button
              onClick={approvePatch}
              className="btn-cyber-primary text-xs"
            >
              Sign-Off & Approve
            </button>
          ) : (
            <span className="text-xs font-mono text-emerald-400 px-3 py-1 rounded bg-emerald-950/60 border border-emerald-500/30">
              ✓ Sign-off Recorded
            </span>
          )}
        </div>
      </div>
    </div>
  );
};
